name: 📺 EPG Request
description: Request to add EPG (Electronic Programming Guide) in this repository

body:
  - type: markdown
    attributes:
      value: |
        Please fill out the issue template as much as you can so we could efficiently process your request

  - type: input
    attributes:
      label: Source
      description: Website where the EPG can be found?
      placeholder: 'https://cablecompany.com/tvlisting'
    validations:
      required: true

  - type: textarea
    attributes:
      label: Notes
      description: 'Anything else that helps? API Url, Etc'