name: 🐞 Bug Report
description: Report an error in this repository
title: 'Fix: '
labels: ['🐞 bug']

body:
  - type: markdown
    attributes:
      value: |
        This form is only for reporting bugs with auto-update, EPG sorting and other problems with automation scripts.

  - type: textarea
    attributes:
      label: Describe your issue
      description: Please describe the error in as much detail as possible so that we can fix it quickly.
    validations:
      required: true
