name: _load
on:
  workflow_call:
    inputs:
      site:
        required: true
        type: string
        
jobs:
  load:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm run api:load
      - uses: FedericoCarboni/setup-ffmpeg@v1
        with:
          token: ${{ secrets.GHPG }}
      - uses: actions/setup-node@v2
        if: ${{ !env.ACT }}
        with:
          node-version: '14'
          cache: 'npm'
      - run: npm install
      - run: CHANNELS_PATH=sites/${{inputs.site}}/*.channels.xml npm run queue:create -- --max-clusters=1 --days=2
      - run: NODE_OPTIONS=--insecure-http-parser npm run cluster:load -- --timeout=30000  --cluster-id=1
      - run: npm run programs:save
      - run: npm run guides:update
      - uses: JamesIves/github-pages-deploy-action@v4.3.3
        if: ${{ !env.ACT && github.ref == 'refs/heads/master' }}
        with:
          branch: gh-pages
          folder: .gh-pages
          token: ${{ secrets.GHPG }}
          git-config-name: liimee
          git-config-email: 70614549+liimee@users.noreply.github.com
          commit-message: 'Update guide'
          clean: false
