name: update epg
on:
  schedule:
    - cron: "0 */24 * * *"
  workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Set up Node
      uses: actions/setup-node@v4
      with:
           node-version: 18

    - name: npm grab epg
      run: |
          npm install
          npm test --- tvtv.us
          
    - name: Commit changes
      run: |
          git config user.name "🧟 Brainz"
          git config user.email "<>"
