name: EPG Test

on:
  workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Set up Node
      uses: actions/setup-node@v4
      with:
           node-version: 18

    - name: npm grab epg
      run: |
          npm install
          #npm run channels:parse --- --config=./sites/canalplus.com/canalplus.com.config.js --output=./sites/canalplus.com/canalplus.com_mu.channels.xml --set=country:mu
          #npm run grab --- --channels=../sites/canalplus.com/canalplus.com_cm.channels.xml--maxConnections=20 --gzip --output=guides/propg.net.xml --days=2 --timeout=90000
          #npm run channels:parse --- --config=./sites/tvepg.eu/tvepg.eu.config.js --output=./sites/tvepg.eu/tvepg.eu.channels.xml
          #npm run channels:parse --- --config=./sites/tv.magenta.me/tv.magenta.me.config.js --output=./sites/tv.magenta.me/tv.magenta.me.channels.xml
          #npm run grab --- --site=tv.magenta.mk --maxConnections=20 --gzip --output=guides/tv.magenta.mk.xml --days=1 --timeout=90000
          #npm run grab --- --site=propg.net --maxConnections=20 --gzip --output=guides/propg.net.xml --days=2 --timeout=90000
          #npm run grab --- --site=hot.net.il --maxConnections=20 --gzip --output=guides/hot.net.il.xml --days=2 --timeout=90000
          npm run grab --- --site=tvplus.com.tr --maxConnections=20 --output=guides/tvplus.com.tr.xml --days=1 --timeout=90000
   
    - name: Commit changes
      run: |
        git config --local user.email "your-email@example.com"
        git config --local user.name "Your Name"
        #git add -f sites/canalplus.com/canalplus.com_mu.channels.xml
        #git add -f guides/tv.magenta.mk.xml
        #git add -f guides/hot.net.il.xml
        git add -f guides/tvplus.com.tr.xml
        #git add -f sites/tvepg.eu/tvepg.eu.channels.xml
        git commit -m "Update xml"
        git push