name: tvtv.us
on:
  schedule:
    - cron: '0/1 * * * *'
  workflow_dispatch:
  workflow_call:
    inputs:
      site:
        required: true
        type: string
    secrets:
      APP_ID:
        required: true
      APP_PRIVATE_KEY:
        required: true
jobs:
  load:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
      - run: npm install
      - run: npx epg-grabber npx epg-grabber --config=./tvtv.us.config.js --channels=./tvtv.us_test.channels.xml --output=./test/tvtv.us.guide.xml --days=3 --gzip

      - uses: actions/upload-artifact@v2
        with:
         name: tvtv.us_${{ steps.date.outputs.date }}
         path: .github/workflows/tvtv.us.yml

      - uses: JamesIves/github-pages-deploy-action@v4.3.3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          branch: gh-pages
          folder: .gh-pages
          clean: false
          force: false
