name: tvtv.us
on:
  schedule:
    - cron: '0/1 * * * *'
  workflow_dispatch:
  workflow_call:
    inputs:
      site:
        required: true
        type: string
    secrets:
      APP_ID:
        required: true
      APP_PRIVATE_KEY:
        required: true
jobs:
  load:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
      - run: npm install
      - name: Run npx epg-grabber
        run: |
          npx epg-grabber --config=./tvtv.us.config.js --channels=./tvtv.us_test.channels.xml --output=./docs/test/tvtv.us.guide.xml --days=3 
          npx epg-grabber --config=./tvtv.us.config.js --channels=./tvtv.us_test.channels.xml --output=./docs/test/tvtv.us.guide.xml.gz --days=3 --gzip

      - name: Check *.xml File existence
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "./docs/test/*.xml, ./docs/test/*.gz"

      - name: If *.xml Files exists - Then Cleanup
        if: steps.check_files.outputs.files_exists == 'true'
        # Only runs if all of the files exists
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          rm ./docs/test/*.xml
          rm ./docs/test/*.xml.gz
          git status
          git push          
          git commit -m "cron: Updated by Bot" -a

      - name: Commit files
        run: |
          git config --local core.autocrlf false
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git config --local user.name "${{ github.actor }}"
          git add . && git add --renormalize .
          git pull origin ${{ github.ref }} --autostash --rebase -X ours
          git commit --allow-empty -am "${{ github.workflow }}"
          NO_PAGER=1 git --no-pager diff HEAD^

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.ref }} 

      - name: Re-pull on failure
        if: ${{ failure() }}
        run: git pull origin ${{ github.ref }} --autostash --rebase -X ours

      - name: Re-push on failure
        if: ${{ failure() }}
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.ref }} 
          force: true

      - name: Push Final Changes
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.ref }}
          force: true 
