name: tvtv.us
on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Set up Node
      uses: actions/setup-node@v4
      with:
           node-version: 18

    - name: npm grab epg
      run: |
          git pull
          npm install
          npm run grab -- --channels=./guide/channels/tvtv.us.channels.xml --gzip --output=./guide/tvtv.us.xml --days=3
          
    - name: Commit changes
      run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git status
          git add -f .guide/tvtv.us.*
          git commit -m "updated epg"
          git push -f origin master
