name: tvtv.us
on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Set up Node
      uses: actions/setup-node@v4
      with:
           node-version: 18

    - name: npm grab epg
      run: |
          npm install
          npm run grab -- --channels=./channels/tvtv.us.channels.xml --gzip --output=./guide/tvtv.us.xml --days=3
          ls ./guide
          
    - name: Commit changes
      run: |
          git config --local user.name "GitHub Action"
          git config --local user.email "action@github.com"
          (git push) || true
          git checkout -B master
          git add -f guide/tvtv.us.xml
          git add -f guide/tvtv.us.xml.gz
          git commit --allow-empty
          git push -f origin master
